name: Trigger repo dispatch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: repo dispatch
        run: echo "repo dispatch"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          repository: evgeniy-scherbina/repo-dispatch-test
          event-type: my-event

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3


